spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*" # 允许所有的请求头过来
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: host_route # 指定的规则的配置的id(标识)
          #uri: http://localhost:18081  # 要转发的请求的路径
          uri: lb://goods
          predicates:
            #- Host=cloud.itheima.com** # 要转发的前提的条件  请求来以cloud.itheima.com 开头的请求 都转发给 http://localhost:18081
            #- Path=/brand/**  # 只要请求的路径 以 /brand开头 的 都符合条件，请求转发给http://localhost:18081
            - Path=/api/goods/**
          filters:
          #  - PrefixPath=/brand # 请求比如：http://localhost:8001/search/1/5 ---> http://localhost:18081/brand/search/1/5
            - StripPrefix=1  #  如果请求：http://localhost:8001/api/brand/search/1/5 -->http://localhost:18081/brand/search/1/5
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
            #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.211.132
    port: 6379

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true